// config/reportEmailTemplate.js
// ============================================================================
//  REPORT DELIVERY EMAIL
//  ----------------------------------------------------------------------
//  Builds a professional, branded HTML email and sends the generated
//  report PDF as an attachment when a Report screen row is "Finalized".
//
//  Uses nodemailer with Gmail, authenticated via the SAME env vars the
//  rest of Verifitech's backend already uses:
//
//    EMAIL_USER=aws500546@gmail.com
//    EMAIL_PASS=xxxxxxxxxxxxxxxx      <- must be a 16-character Gmail
//                                        APP PASSWORD, not the normal
//                                        Gmail account password (Gmail
//                                        rejects the account password for
//                                        SMTP login when 2FA is on, and
//                                        Google no longer allows "less
//                                        secure app" access at all).
//                                        Generate one at:
//                                        https://myaccount.google.com/apppasswords
//                                        (requires 2-Step Verification to
//                                        be turned on for the account first)
//
//  If EMAIL_USER / EMAIL_PASS are missing (or still a placeholder like
//  the "t" in a fresh .env), sending is SIMULATED instead of thrown —
//  logged to the console, check still marked finalized — so local
//  development is never blocked waiting on real Gmail credentials.
// ============================================================================

const nodemailer = require('nodemailer');
const path = require('path');
const fs = require('fs');

const LOGO_PATH = path.join(__dirname, '..', 'images', 'verifitech-logoo.png');
const LOGO_CID = 'verifitech-logo';

// A real Gmail app password is always 16 characters (letters only, no
// spaces once copied). Anything shorter — like a leftover placeholder
// value such as "t" — is treated as "not configured yet" so we fall back
// to the simulated transport instead of letting Gmail reject the login
// and throw a confusing auth error.
function hasValidEmailConfig() {
  const user = process.env.EMAIL_USER;
  const pass = process.env.EMAIL_PASS;
  return !!user && !!pass && pass.replace(/\s+/g, '').length >= 16;
}

function createTransporter(isConfigured) {
  if (!isConfigured) {
    // No usable Gmail credentials yet — nodemailer's JSON transport never
    // dials out anywhere, so Finalize & Send / Resend can't fail with a
    // connection or auth error while EMAIL_PASS is still a placeholder.
    return nodemailer.createTransport({ jsonTransport: true });
  }

  return nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });
}

const fmtDate = (d) => {
  if (!d) return '';
  const dt = new Date(d);
  if (Number.isNaN(dt.getTime())) return '';
  return dt.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
};

function buildReportEmailHtml({ candidateName, bgvRef, checkType, subType, clientName, finalStatus }) {
  const statusColor = finalStatus === 'GENUINE' ? '#16a34a'
    : finalStatus === 'ADVERSE REMARK REPORT' ? '#dc2626'
    : finalStatus === 'INFORMATION UNABLE TO VALIDATE' ? '#d97706'
    : '#ea580c';

  return `
  <div style="font-family: 'Segoe UI', Arial, sans-serif; background:#f4f7f6; padding:32px 0;">
    <div style="max-width:600px; margin:0 auto; background:#ffffff; border-radius:12px; overflow:hidden; border:1px solid #e2e8f0;">
      <div style="background:#c2f2f1; padding:24px 32px; display:flex; align-items:center;">
        <img src="cid:${LOGO_CID}" alt="Verifitech" style="height:100px; width:150px;" />
      </div>
      <div style="padding:32px;">
        <p style="font-size:11px; letter-spacing:1px; color:#0ea5a4; font-weight:700; text-transform:uppercase; margin:0 0 8px;">
          Verification Report Delivered
        </p>
        <h2 style="font-size:20px; color:#0f172a; margin:0 0 16px;">Report for ${candidateName || 'Candidate'}</h2>
        <p style="font-size:14px; color:#475569; line-height:1.6; margin:0 0 20px;">
          Dear ${clientName || 'Team'},<br /><br />
          Please find attached the completed and QC-approved verification report for the candidate referenced
          below. This report has been generated by Verifitech's verification and quality-control workflow and
          is ready for your records.
        </p>

        <table style="width:100%; border-collapse:collapse; font-size:13px; color:#0f172a;">
          <tr>
            <td style="padding:8px 0; border-bottom:1px solid #e2e8f0; color:#64748b; width:40%;">Case Ref. No</td>
            <td style="padding:8px 0; border-bottom:1px solid #e2e8f0; font-weight:600;">${bgvRef || '—'}</td>
          </tr>
          <tr>
            <td style="padding:8px 0; border-bottom:1px solid #e2e8f0; color:#64748b;">Candidate Name</td>
            <td style="padding:8px 0; border-bottom:1px solid #e2e8f0; font-weight:600;">${candidateName || '—'}</td>
          </tr>
          <tr>
            <td style="padding:8px 0; border-bottom:1px solid #e2e8f0; color:#64748b;">Verification Type</td>
            <td style="padding:8px 0; border-bottom:1px solid #e2e8f0; font-weight:600;">${checkType || '—'}${subType ? ` (${subType})` : ''}</td>
          </tr>
          <tr>
            <td style="padding:8px 0; color:#64748b;">Report Date</td>
            <td style="padding:8px 0; font-weight:600;">${fmtDate(new Date())}</td>
          </tr>
        </table>

        <div style="margin-top:20px; padding:12px 16px; border-radius:8px; background:${statusColor}1a; border:1px solid ${statusColor}55;">
          <span style="font-size:11px; font-weight:700; letter-spacing:0.5px; color:${statusColor};">FINAL STATUS: ${finalStatus || 'GENUINE'}</span>
        </div>

        <p style="font-size:13px; color:#94a3b8; line-height:1.6; margin-top:28px;">
          This is a system-generated notification from Verifitech's Background Verification platform.
          For any queries regarding this report, please reach out to your Verifitech account contact or
          write to <a href="mailto:verify@verifitech.com" style="color:#0ea5a4;">verify@verifitech.com</a>.
        </p>
      </div>
      <div style="background:#f8fafc; padding:16px 32px; border-top:1px solid #e2e8f0; text-align:center;">
        <p style="font-size:11px; color:#94a3b8; margin:0;">
          Verifitech India Info Pvt. Ltd. &middot; Strictly Private &amp; Confidential
        </p>
      </div>
    </div>
  </div>`;
}

// sendReportDeliveryEmail({ to, candidateName, bgvRef, checkType, subType,
//   clientName, finalStatus, pdfBuffer, fileName })
// Returns { success, messageId, simulated }.
async function sendReportDeliveryEmail({
  to, candidateName, bgvRef, checkType, subType, clientName, finalStatus, pdfBuffer, fileName,
}) {
  if (!to) throw new Error('A client email address is required.');
  if (!pdfBuffer) throw new Error('No PDF was provided to attach.');

  const isConfigured = hasValidEmailConfig();
  const transporter = createTransporter(isConfigured);

  const attachments = [
    {
      filename: fileName || 'Verification_Report.pdf',
      content: pdfBuffer,
      contentType: 'application/pdf',
    },
  ];

  if (fs.existsSync(LOGO_PATH)) {
    attachments.push({
      filename: 'verifitech-logo.png',
      path: LOGO_PATH,
      cid: LOGO_CID,
    });
  }

  const html = buildReportEmailHtml({ candidateName, bgvRef, checkType, subType, clientName, finalStatus });

  const info = await transporter.sendMail({
    from: process.env.EMAIL_FROM || `"Verifitech Reports" <${process.env.EMAIL_USER || 'reports@verifitech.com'}>`,
    to,
    subject: `Verification Report — ${candidateName || 'Candidate'} (${bgvRef || ''})`,
    html,
    attachments,
  });

  if (!isConfigured) {
    console.log('\n📧 [DEV MODE] EMAIL_USER / EMAIL_PASS not set (or EMAIL_PASS is a placeholder) — email simulated, not actually sent.');
    console.log(`    Would have sent to: ${to}`);
    console.log(`    Subject: Verification Report — ${candidateName || 'Candidate'} (${bgvRef || ''})`);
    console.log('    Set EMAIL_USER to a Gmail address and EMAIL_PASS to a 16-character Gmail');
    console.log('    App Password (https://myaccount.google.com/apppasswords) to send real emails.\n');
  }

  return { success: true, messageId: info.messageId, simulated: !isConfigured };
}

module.exports = { sendReportDeliveryEmail, buildReportEmailHtml };